# src/data_prepro.py

import os
import sys

# Add the project root to the Python path to allow for absolute imports
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(PROJECT_ROOT)

# Import the specific preprocessing function for synthetic data
from src.custom_data_generation.data_prepro import preprocess_synthetic_data

def preprocess_data():
    """
    Main entry point for all data preprocessing tasks.
    This script acts as a dispatcher, calling specific preprocessing
    functions for different types of raw data.
    """
    print("--- Starting Master Data Preprocessing Script ---")

    # --- 1. Process Synthetic Data ---
    # This data is generated by our custom scripts.
    preprocess_synthetic_data()

    # --- 2. Process Other Raw Data (Placeholder) ---
    # TODO: Implement preprocessing for other data sources when they are added.
    # For example, you might have experimental data:
    # from src.experimental_data.prepro import preprocess_experimental_data
    # preprocess_experimental_data()
    print("\nPlaceholder: No other data sources to process at this time.")


    print("\n--- Master Data Preprocessing Complete ---")

if __name__ == "__main__":
    preprocess_data()