# src/data_prepro.py

import os
import sys

# Add the project root to the Python path to allow for absolute imports
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(PROJECT_ROOT)

# Import the specific preprocessing function for synthetic data
from src.custom_data_generation.data_prepro import preprocess_synthetic_data

def preprocess_data(target_file=None):
    """
    Main entry point for all data preprocessing tasks.
    This script acts as a dispatcher, calling specific preprocessing
    functions for different types of raw data.

    Args:
        target_file (str, optional): A specific raw data file to preprocess.
                                     If None, all raw data will be processed.
    """
    print("--- Starting Master Data Preprocessing Script ---")

    # --- 1. Process Synthetic Data ---
    # This data is generated by our custom scripts.
    preprocess_synthetic_data(target_file=target_file)

    # --- 2. Process Other Raw Data (Placeholder) ---
    # TODO: Implement preprocessing for other data sources when they are added.
    # This section would also need to be updated to handle the `target_file` argument.
    if not target_file:
        print("\nPlaceholder: No other data sources to process at this time.")


    print("\n--- Master Data Preprocessing Complete ---")

if __name__ == "__main__":
    # When run directly, process all data by default.
    preprocess_data()